let communityLoaded=false,communityData=null,communityRunning=false,communityReady=false,restoreDraft=null;
const ccFields=[];
function ccNode(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function ccCard(parent,title,desc){const box=ccNode('div',undefined,'card');box.append(ccNode('h2',title),ccNode('p',desc));parent.append(box);return box}
function ccField(parent,key,label,type='text',help='',list=''){ccFields.push(key);const l=ccNode('label',label);l.htmlFor='cc_'+key;const el=ccNode(type==='textarea'?'textarea':'input');el.id='cc_'+key;if(type==='textarea')el.rows=3;else el.type=type;if(list)el.setAttribute('list',list);if(type==='checkbox'){l.className='check';l.prepend(el);parent.append(l)}else parent.append(l,el);if(help)parent.append(ccNode('small',help));return el}
function ccButton(parent,id,text,fn,live=false){const b=ccNode('button',text);b.id=id;b.type='button';if(live)b.dataset.communityLive='1';b.onclick=()=>action(b,fn);parent.append(b);return b}
function ccInput(parent,id,label,type='text',list=''){const l=ccNode('label',label);l.htmlFor=id;const el=ccNode(type==='textarea'?'textarea':type==='select'?'select':'input');el.id=id;if(type==='textarea')el.rows=3;else if(type!=='select')el.type=type;if(list)el.setAttribute('list',list);parent.append(l,el);return el}
function ccRows(container,values,kind){container.replaceChildren();for(const value of values)ccAddRow(container,kind,value)}
function ccAddRow(container,kind,value={}){if(container.children.length>=(kind==='role'?22:30)){toast('Entry limit reached.',true);return}const row=ccNode('div',undefined,'embed-field-editor');const keys=kind==='role'?['label','role_id','description']:['name','text'];const labels=kind==='role'?['Role label','Role ID','Short description (optional)']:['Topic name','Answer'];for(let j=0;j<keys.length;j++){const key=keys[j],el=ccInput(row,'',labels[j],key==='text'?'textarea':'text',key==='role_id'?'roles':'');el.removeAttribute('id');row.querySelector('label:last-of-type').removeAttribute('for');el.dataset.key=key;el.value=value[key]||'';el.maxLength={label:80,role_id:22,description:100,name:32,text:1800}[key]}const remove=ccNode('button','Remove');remove.type='button';remove.onclick=()=>row.remove();row.append(remove);container.append(row)}
function ccReadRows(container){return [...container.children].map(row=>{const o={};for(const el of row.querySelectorAll('[data-key]'))o[el.dataset.key]=el.value;return o})}
function readCommunity(){const c={};for(const key of ccFields){const el=$('cc_'+key);c[key]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value}c.self_roles=ccReadRows($('cc_roles'));c.faq=ccReadRows($('cc_faq'));c.ticket_staff_roles=c.ticket_staff_roles.split(/[\s,]+/).filter(Boolean);return c}
function setCommunity(c){for(const key of ccFields){const el=$('cc_'+key);if(el.type==='checkbox')el.checked=!!c[key];else el.value=Array.isArray(c[key])?c[key].join(', '):(c[key]??'')}ccRows($('cc_roles'),c.self_roles||[],'role');ccRows($('cc_faq'),c.faq||[],'faq')}
function communityStatus(s){communityRunning=s.running;communityReady=s.ready;if($('cc_form'))$('cc_form').disabled=s.running||working;if($('cc_save'))$('cc_save').disabled=s.running||working;for(const b of document.querySelectorAll('[data-community-live]'))b.disabled=!s.ready||working;if($('cc_restore'))$('cc_restore').disabled=s.running||working||!restoreDraft;if($('cc_backup'))$('cc_backup').disabled=working}
async function loadCommunity(overwrite=false){const r=await api('community');communityData=r;if(!communityLoaded||overwrite){setCommunity(r.config);communityLoaded=true}renderCommunityRecords();communityStatus({running:communityRunning,ready:communityReady});return r}
function ccLink(url,label){const a=ccNode('a',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a}
function renderCommunityRecords(){const r=communityData;if(!r)return;const summary=$('cc_summary');summary.textContent=Object.values(r.tickets).filter(t=>!t.closed).length+' open tickets · '+r.submissions.length+' submissions · '+Object.keys(r.voice_rooms).length+' voice rooms';const until=new Date(r.raid_until);$('cc_raid_status').textContent=until>Date.now()?'Raid mode active until '+until.toLocaleString():'Raid mode is inactive.';$('cc_native_status').textContent=Object.keys(r.native_rules).length?'Saved Discord AutoMod rules: '+Object.keys(r.native_rules).join(', '):'No Discord AutoMod rules applied yet.';
 const list=$('cc_panels');list.replaceChildren();for(const p of Object.values(r.panels)){const line=ccNode('p');line.append(ccLink('https://discord.com/channels/'+$('guild_id').value+'/'+p.channel_id+'/'+p.message_id,p.kind+' panel'));list.append(line)}if(!list.children.length)list.append(ccNode('p','No community panels posted yet.'));
 const tickets=$('cc_ticket_list');tickets.replaceChildren();for(const t of Object.values(r.tickets).sort((a,b)=>new Date(b.created)-new Date(a.created)).slice(0,100)){const row=ccNode('div',undefined,'embed-field-editor');row.append(ccLink('https://discord.com/channels/'+$('guild_id').value+'/'+t.channel_id,t.subject),ccNode('small','Owner '+t.owner+' · '+(t.closed?'Closed':'Open')));const b=ccNode('button',t.closed?'Reopen':'Close');b.dataset.communityLive='1';b.onclick=()=>action(b,async()=>{await api('community-ticket',{id:t.id,closed:!t.closed});await loadCommunity();toast('Ticket updated. Its private history is retained.')});row.append(b);tickets.append(row)}if(!tickets.children.length)tickets.append(ccNode('p','No tickets yet.'));
 const subs=$('cc_submission_list');subs.replaceChildren();for(const x of r.submissions.slice(0,50)){const row=ccNode('p');row.append(ccLink('https://discord.com/channels/'+$('guild_id').value+'/'+x.channel_id+'/'+x.message_id,x.title+' · '+x.status),ccNode('small',x.kind+' · submitted by '+x.author));subs.append(row)}if(!subs.children.length)subs.append(ccNode('p','No submissions yet.'));
 const events=$('cc_event_list');events.replaceChildren();for(const e of Object.values(r.events).sort((a,b)=>new Date(b.starts)-new Date(a.starts)).slice(0,50)){const row=ccNode('div',undefined,'embed-field-editor');row.append(ccLink('https://discord.com/events/'+$('guild_id').value+'/'+e.id,e.name),ccNode('small',new Date(e.starts).toLocaleString()+' · '+(e.cancelled?'Cancelled':e.reminded?'Reminder sent':e.reminder_minutes?'Reminder scheduled':'No reminder')));if(!e.cancelled){const b=ccNode('button','Cancel event');b.dataset.communityLive='1';b.onclick=()=>action(b,async()=>{await api('community-event-cancel',{id:e.id});await loadCommunity();toast('Event cancelled.')});row.append(b)}events.append(row)}
 renderCommunityCases();
}
function renderCommunityCases(){const out=$('cc_cases');out.replaceChildren();const q=$('cc_case_search').value.trim().toLowerCase();for(const x of [...(communityData?.cases||[])].reverse()){if(q&&!JSON.stringify(x).toLowerCase().includes(q))continue;const d=ccNode('details',undefined,'embed-field-editor');d.append(ccNode('summary','#'+x.id+' · '+x.kind+' · '+(x.target||x.channel_id)+' · '+(x.reversed_by?'Reversed':'Recorded')));d.append(ccNode('p',x.reason),ccNode('small','By '+x.actor+' · '+new Date(x.created).toLocaleString()));if(x.note)d.append(ccNode('p',x.note));if(x.until)d.append(ccNode('small','Until '+new Date(x.until).toLocaleString()));if(x.reversed_by)d.append(ccNode('small','Reversed by '+x.reversed_by+' in case #'+x.reversal_case));const note=ccNode('input');note.placeholder='Staff note (up to 400 characters)';note.maxLength=400;note.setAttribute('aria-label','Note for case '+x.id);d.append(note);const save=ccNode('button','Save note');save.onclick=()=>action(save,async()=>{await api('community-case-note',{id:x.id,note:note.value});await loadCommunity();toast('Case note saved.')});d.append(save);if(!x.reversed_by&&['warn','ban','timeout','raid-timeout'].includes(x.kind)){const reason=ccNode('input');reason.placeholder='Reason for reversing this action';reason.maxLength=400;reason.setAttribute('aria-label','Reversal reason for case '+x.id);const label=ccNode('label','I want to reverse this case','check');const confirm=ccNode('input');confirm.type='checkbox';label.prepend(confirm);const reverse=ccNode('button','Reverse action');reverse.dataset.communityLive='1';reverse.onclick=()=>action(reverse,async()=>{const r=await api('community-case-reverse',{id:x.id,reason:reason.value,confirm:confirm.checked});await loadCommunity();toast(r.message)});d.append(reason,label,reverse)}out.append(d)}if(!out.children.length)out.append(ccNode('p','No matching cases.'))}
function setupCommunity(){const parent=$('communityView');const intro=ccCard(parent,'Community toolkit','Stop the bot to edit settings, save, then start it to publish panels or use community tools. Existing messages and records survive restarts.');intro.append(ccNode('p','', 'meta'));intro.lastChild.id='cc_summary';const actions=ccNode('div',undefined,'row');intro.append(actions);ccButton(actions,'cc_save','Save community settings',async()=>{const r=await api('community-save',readCommunity());setCommunity(r.config);toast('Community settings saved. Start the bot, then publish or update your panels.');await loadCommunity()});ccButton(actions,'cc_refresh','Refresh records',async()=>loadCommunity());ccButton(actions,'cc_inspect','Check community setup',async()=>{await loadIDs();$('cc_check_result').textContent=$('checks').textContent;toast('Setup checked. See the results below.')},true);const checks=ccNode('pre',undefined,'log');checks.id='cc_check_result';intro.append(checks);
 const form=ccNode('fieldset');form.id='cc_form';parent.append(form);const grid=ccNode('div',undefined,'two');form.append(grid);
 let card=ccCard(grid,'Welcome & onboarding','Welcome messages are sent after membership screening. Leave the welcome channel empty to disable.');ccField(card,'welcome_channel','Welcome channel','text','','channels');ccField(card,'welcome_text','Welcome message','textarea','Placeholders: {user}, {server}, {rules}, {roles}, {showcase}. Only the new member is pinged.');ccField(card,'rules_channel','Rules channel','text','','channels');ccField(card,'showcase_channel','Showcase channel','text','','channels');
 card=ccCard(grid,'Interest roles & notifications','Members can opt in and out through a dropdown. Staff and management roles are rejected.');ccField(card,'roles_channel','Role-menu channel','text','','channels');ccField(card,'live_role','Livestream ping role','text','','roles');ccField(card,'release_role','Mod / shader release ping role','text','','roles');card.append(ccNode('small','Your upload ping role from Bot settings is also included automatically. Make notification roles mentionable.'));const roles=ccNode('div');roles.id='cc_roles';card.append(roles);const add=ccNode('button','Add interest role');add.type='button';add.onclick=()=>ccAddRow(roles,'role');card.append(add);
 card=ccCard(grid,'Private tickets & reports','Reports and requests get a private text channel. Closing retains the channel and history; the owner can read it but cannot send.');ccField(card,'ticket_panel_channel','Ticket-panel channel','text','','channels');ccField(card,'ticket_category','Ticket category (optional)','text','','categories');ccField(card,'ticket_staff_roles','Staff role IDs','textarea','Separate multiple IDs with commas. These roles and server administrators can see tickets.');
 card=ccCard(grid,'Ideas & bug reports','Public submissions have voting buttons and a status menu restricted to moderators.');ccField(card,'submission_panel_channel','Submission-panel channel','text','','channels');ccField(card,'suggest_channel','Suggestion channel','text','','channels');ccField(card,'bug_channel','Bug-report channel','text','','channels');
 card=ccCard(grid,'Release & livestream announcements','Use the posting tools below or /release and /live. Livestream announcements are manual. YouTube upload detection remains automatic.');ccField(card,'release_channel','Release channel','text','','channels');ccField(card,'live_channel','Livestream channel','text','','channels');ccField(card,'event_channel','Event announcement / reminder channel','text','','channels');
 card=ccCard(grid,'Temporary voice rooms','Joining the lobby creates a room and moves the member into it. Empty rooms are removed after a short grace period. /voice lets the owner rename it or set its size.');ccField(card,'voice_lobby','Create-a-room voice channel','text','Leave blank to disable.','voicechannels');ccField(card,'voice_category','Temporary-room category','text','','categories');const limit=ccField(card,'voice_limit','Default member limit','number');limit.min=1;limit.max=99;
 card=ccCard(grid,'Anti-raid protection','Join spikes trigger temporary newcomer timeouts. Mass mentions are deleted and timed out. This does not ban people for account age or joining.');ccField(card,'raid_enabled','Enable join-spike and mass-mention protection','checkbox');for(const [key,label,min,max] of [['raid_joins','Join threshold',3,100],['raid_window','Join window (seconds)',5,120],['raid_minutes','Restriction duration (minutes)',1,60],['mention_limit','Unique mentions allowed per message',2,50]]){const el=ccField(card,key,label,'number');el.min=min;el.max=max}
 card=ccCard(grid,'Discord AutoMod','Native keyword and mention filters keep blocking messages while your PC is offline. Online, a blocked listed slur still triggers your ban policy.');ccField(card,'native_automod','Enable native Discord filters','checkbox','Uses the slur list in Bot settings and mention limit above. Save, start the bot, then press Apply Discord AutoMod. Disabling here also requires applying to turn native rules off.');
 card=ccCard(grid,'FAQ commands','/mods, /shaders, /youtube and /support show matching answers. Other entries are available through /faq topic:your-topic.');const faq=ccNode('div');faq.id='cc_faq';card.append(faq);const more=ccNode('button','Add FAQ topic');more.type='button';more.onclick=()=>ccAddRow(faq,'faq');card.append(more);
 const tools=ccNode('div',undefined,'two');parent.append(tools);
 card=ccCard(tools,'Publish community panels','Publishing again updates the existing panel in its configured channel. Changing channels creates a new panel.');const row=ccNode('div',undefined,'row');card.append(row);for(const [kind,label] of [['roles','Publish role menu'],['ticket','Publish ticket panel'],['submissions','Publish submission panel']])ccButton(row,'cc_publish_'+kind,label,async()=>{const r=await api('community-publish',{kind});await loadCommunity();toast('Panel published. Open its link below.')},true);const panels=ccNode('div');panels.id='cc_panels';card.append(panels);
 card=ccCard(tools,'Protection controls','These buttons apply saved settings. Discord-owned filters have their own availability rules and do not make the bot immune to removal.');ccButton(card,'cc_apply_automod','Apply Discord AutoMod',async()=>{await api('community-automod',{});await loadCommunity();toast('Discord AutoMod synchronized.')},true);const native=ccNode('p');native.id='cc_native_status';card.append(native);const raid=ccNode('p');raid.id='cc_raid_status';card.append(raid);const minutes=ccInput(card,'cc_raid_duration','Manual raid-mode duration (minutes)','number');minutes.value=10;minutes.min=1;minutes.max=60;const raidrow=ccNode('div',undefined,'row');card.append(raidrow);ccButton(raidrow,'cc_raid_on','Enable raid mode',async()=>{await api('community-raid',{active:true,minutes:Number(minutes.value)});await loadCommunity();toast('Raid mode enabled. Newcomers receive temporary restrictions.')},true);ccButton(raidrow,'cc_raid_off','End raid mode',async()=>{await api('community-raid',{active:false,minutes:0});await loadCommunity();toast('Raid mode ended; matching newcomer timeouts removed.')},true);
 card=ccCard(tools,'Publish a release or livestream','Only the matching opt-in notification role is pinged.');const kind=ccInput(card,'cc_post_kind','Announcement type','select');for(const [value,label]of [['release','Mod / shader release'],['live','Live now']]){const op=ccNode('option',label);op.value=value;kind.append(op)}ccInput(card,'cc_post_title','Project / stream title');ccInput(card,'cc_post_version','Version (releases)');ccInput(card,'cc_post_text','Changes / announcement text','textarea');ccInput(card,'cc_post_url','Download / stream link (HTTPS)');ccButton(card,'cc_post','Publish announcement',async()=>{const r=await api('community-announcement',{kind:kind.value,title:$('cc_post_title').value,version:$('cc_post_version').value,text:$('cc_post_text').value,url:$('cc_post_url').value});$('cc_post_result').replaceChildren(ccLink(r.url,'Open announcement'));toast('Announcement posted.')},true);const result=ccNode('p');result.id='cc_post_result';card.append(result);
 card=ccCard(tools,'Community poll','Native Discord polls keep collecting votes and close automatically even if the bot goes offline.');ccInput(card,'cc_poll_channel','Poll channel','text','channels');ccInput(card,'cc_poll_question','Question');ccInput(card,'cc_poll_answers','Answers — one per line (2–10)','textarea');const hours=ccInput(card,'cc_poll_hours','Duration (hours)','number');hours.value=24;hours.min=1;hours.max=768;const multiple=ccInput(card,'cc_poll_multiple','Allow multiple answers','checkbox');ccButton(card,'cc_poll','Post poll',async()=>{const r=await api('community-poll',{channel_id:$('cc_poll_channel').value,question:$('cc_poll_question').value,answers:$('cc_poll_answers').value.split('\n').filter(s=>s.trim()),hours:Number(hours.value),multiple:multiple.checked});$('cc_poll_result').replaceChildren(ccLink(r.url,'Open poll'));toast('Poll posted.')},true);const pollresult=ccNode('p');pollresult.id='cc_poll_result';card.append(pollresult);
 card=ccCard(tools,'Schedule a community event','Creates a Discord event with RSVP. Reminders are sent while the bot is online; a reminder missed after the event starts is skipped.');ccInput(card,'cc_event_name','Event name');ccInput(card,'cc_event_description','Description','textarea');ccInput(card,'cc_event_start','Start','datetime-local');ccInput(card,'cc_event_end','End','datetime-local');card.append(ccNode('small','Dates use your computer timezone: '+Intl.DateTimeFormat().resolvedOptions().timeZone));ccInput(card,'cc_event_location','Location / link');ccInput(card,'cc_event_post_channel','Announcement / reminder channel','text','channels');ccInput(card,'cc_event_role','Optional reminder role','text','roles');const mins=ccInput(card,'cc_event_reminder','Remind this many minutes before start (0 = none)','number');mins.value=30;mins.min=0;mins.max=1440;ccButton(card,'cc_create_event','Create event',async()=>{const start=new Date($('cc_event_start').value),end=new Date($('cc_event_end').value);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime()))throw Error('Choose both event dates.');await api('community-event',{name:$('cc_event_name').value,description:$('cc_event_description').value,start:start.toISOString(),end:end.toISOString(),location:$('cc_event_location').value,channel_id:$('cc_event_post_channel').value,role_id:$('cc_event_role').value,reminder_minutes:Number(mins.value)});await loadCommunity();toast('Discord event created.')},true);const eventlist=ccNode('div');eventlist.id='cc_event_list';card.append(eventlist);
 card=ccCard(tools,'Backups','Export settings, warnings, embeds, cases and community bindings. Tokens are excluded. Restoring replaces saved data for the same server and keeps your current token. Discord message history and channel contents are not included.');ccButton(card,'cc_backup','Download backup',async()=>{const r=await api('community-backup',{});const blob=new Blob([JSON.stringify(r,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=ccNode('a');a.href=url;a.download='MubbleDiscordBot-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup downloaded without the bot token.')});const upload=ccInput(card,'cc_backup_file','Choose a backup to restore','file');upload.accept='.json,application/json';upload.onchange=async()=>{restoreDraft=null;const file=upload.files[0];if(!file)return;if(file.size>64*1024*1024){toast('Use a backup under 64 MB.',true);return}try{restoreDraft=JSON.parse(await file.text());$('cc_restore_summary').textContent='Selected '+file.name+' · server '+restoreDraft.config?.guild_id+' · saved '+restoreDraft.created;communityStatus({running:communityRunning,ready:communityReady})}catch{toast('That file is not a JSON backup.',true)}};const restoreSummary=ccNode('p');restoreSummary.id='cc_restore_summary';card.append(restoreSummary);ccButton(card,'cc_restore','Restore selected backup',async()=>{if(!restoreDraft)throw Error('Choose a backup first.');await api('community-restore',restoreDraft);initial=true;await loadCommunity(true);toast('Backup restored. Your token was kept.');restoreDraft=null;upload.value='';restoreSummary.textContent=''});
 card=ccCard(tools,'Private tickets','Open the channel to read its full history. Closed tickets remain private.');const ticketlist=ccNode('div');ticketlist.id='cc_ticket_list';card.append(ticketlist);
 card=ccCard(tools,'Suggestions & bug reports','Open a submission to vote or change its status in Discord. Status changes require Manage Messages.');const sublist=ccNode('div');sublist.id='cc_submission_list';card.append(sublist);
 card=ccCard(parent,'Moderation cases','Latest 100 cases are shown here. Use /cases member:… for member history, /case for details, /case-note for notes, and /case-reverse to undo an eligible action.');const search=ccInput(card,'cc_case_search','Search cases');search.oninput=renderCommunityCases;const cases=ccNode('div');cases.id='cc_cases';card.append(cases);
 $('communityTab').onclick=()=>{switchBotTab('community');loadCommunity().catch(e=>toast(e.message,true))};communityStatus({running:communityRunning,ready:communityReady});loadCommunity().catch(e=>toast(e.message,true));
}
setupCommunity();
