const embKeys=['name','channel_id','content','title','description','color','url','author','author_icon','image','thumbnail','footer','mode','role_id','button_label','button_style','emoji'];
let embID='',embPosts=[],embBlank=null,embPublished=null;
function readEmbed(){const d={id:embID,fields:[]};for(const f of embKeys)d[f]=$('emb_'+f).value;for(const el of $('emb_fields').children)d.fields.push({name:el.querySelector('input[type=text]').value,value:el.querySelector('textarea').value,inline:el.querySelector('input[type=checkbox]').checked});return d}
function safeImage(el,url){const valid=/^https:\/\//i.test(url);el.hidden=!valid;if(valid)el.src=url;else el.removeAttribute('src')}
function previewMarkdown(el,text){el.replaceChildren();const re=/\*\*([\s\S]+?)\*\*|`([^`]+)`|\[([^\]]+)\]\((https:\/\/[^\s)]+)\)/g;let from=0,m;while((m=re.exec(text))){el.append(document.createTextNode(text.slice(from,m.index)));let node;if(m[1]!==undefined){node=document.createElement('strong');node.textContent=m[1]}else if(m[2]!==undefined){node=document.createElement('code');node.textContent=m[2]}else{node=document.createElement('a');node.textContent=m[3];node.href=m[4];node.target='_blank';node.rel='noopener noreferrer'}el.append(node);from=re.lastIndex}el.append(document.createTextNode(text.slice(from)))}
function renderEmbed(){const d=readEmbed();$('emb_preview').style.borderLeftColor=d.color;$('emb_preview_above').textContent=d.content;$('emb_preview_author').textContent=d.author;$('emb_preview_title').textContent=d.title;previewMarkdown($('emb_preview_description'),d.description);safeImage($('emb_preview_icon'),d.author_icon);safeImage($('emb_preview_thumb'),d.thumbnail);safeImage($('emb_preview_image'),d.image);$('emb_preview_footer').textContent=d.footer;const fields=$('emb_preview_fields');fields.replaceChildren();for(const f of d.fields){const box=document.createElement('div');box.className='embed-preview-field'+(f.inline?' inline':'');const title=document.createElement('strong');title.textContent=f.name;const content=document.createElement('div');previewMarkdown(content,f.value);box.append(title,content);fields.append(box)}
$('emb_role_options').hidden=d.mode==='none';$('emb_button_options').hidden=d.mode!=='button';$('emb_reaction_options').hidden=d.mode!=='reaction';$('emb_preview_button').hidden=d.mode!=='button';$('emb_preview_reaction').hidden=d.mode!=='reaction';$('emb_preview_button').textContent=d.button_label||"I've read the rules";$('emb_preview_button').style.background={red:'#da373c',green:'#248046',blue:'#5865f2',grey:'#4e5058'}[d.button_style]||'#da373c';$('emb_preview_button').style.borderColor='transparent';$('emb_preview_reaction').textContent=(d.emoji||'✅')+' 1';const n=[...d.description].length;let total=[...d.title+d.description+d.author+d.footer].length;for(const f of d.fields)total+=[...f.name+f.value].length;$('emb_count').textContent=n+' / 4096 description characters · '+total+' / 6000 embed characters';$('emb_addfield').disabled=d.fields.length>=25;$('emb_publish').textContent=embPublished?'Update posted message':'Publish message'}
function addEmbedField(f={name:'',value:'',inline:false}){if($('emb_fields').children.length>=25)return;const box=document.createElement('div');box.className='embed-field-editor';const nameLabel=document.createElement('label');nameLabel.textContent='Field name';const name=document.createElement('input');name.type='text';name.maxLength=256;name.value=f.name;nameLabel.append(name);const textLabel=document.createElement('label');textLabel.textContent='Field text';const value=document.createElement('textarea');value.rows=3;value.maxLength=1024;value.value=f.value;textLabel.append(value);const row=document.createElement('div');row.className='row';const inlineLabel=document.createElement('label');inlineLabel.className='check';const inline=document.createElement('input');inline.type='checkbox';inline.checked=!!f.inline;inlineLabel.append(inline,document.createTextNode('Display inline'));const remove=document.createElement('button');remove.type='button';remove.textContent='Remove field';remove.onclick=()=>{box.remove();renderEmbed()};row.append(inlineLabel,remove);box.append(nameLabel,textLabel,row);for(const el of [name,value,inline])el.addEventListener('input',renderEmbed);$('emb_fields').append(box)}
function setEmbed(d,published=null){embID=d.id||'';embPublished=published;for(const f of embKeys)$('emb_'+f).value=d[f]??'';if(!d.color)$('emb_color').value='#ed4245';$('emb_fields').replaceChildren();for(const f of d.fields||[])addEmbedField(f);$('emb_select').value=embID;$('emb_published_meta').textContent=published?'Published message '+published.message_id+'. Saving a draft does not change it until you click Update.':'This message has not been published.';$('emb_post_link').hidden=!published;if(published){const p=embPosts.find(p=>p.id===embID);if(p)$('emb_post_link').href='https://discord.com/channels/'+p.guild_id+'/'+published.channel_id+'/'+published.message_id}renderEmbed()}
async function loadEmbeds(){const r=await api('embeds');embPosts=r.posts;embBlank=r.blank;const select=$('emb_select');select.replaceChildren();const blank=document.createElement('option');blank.value='';blank.textContent='New message';select.append(blank);for(const p of embPosts){const option=document.createElement('option');option.value=p.id;option.textContent=p.draft.name+(p.published?' · posted':' · draft');select.append(option)}select.value=embID}
function blankEmbed(){const d=JSON.parse(JSON.stringify(embBlank||{name:'New message',color:'#ed4245',author:'Mubble’s Workshop',mode:'none',button_label:"I've read the rules",button_style:'red',emoji:'✅',fields:[]}));d.channel_id=$('emb_channel_id').value;return d}
function switchBotTab(which){$('communityView').hidden=which!=='community';$('communityTab').className=which==='community'?'primary':'';$('embedsView').hidden=which!=='embeds';$('settingsView').hidden=which!=='settings';$('settingsTab').className=which==='settings'?'primary':'';$('embedsTab').className=which==='embeds'?'primary':'';if(which==='embeds')loadEmbeds().catch(e=>toast(e.message,true))}
$('settingsTab').onclick=()=>switchBotTab('settings');$('embedsTab').onclick=()=>switchBotTab('embeds');for(const f of embKeys)$('emb_'+f).addEventListener('input',renderEmbed);
$('emb_select').onchange=()=>{const p=embPosts.find(p=>p.id===$('emb_select').value);setEmbed(p?p.draft:blankEmbed(),p?p.published:null)};
$('emb_new').onclick=()=>setEmbed(blankEmbed());$('emb_copy').onclick=()=>{const d=readEmbed();d.id='';d.name=(d.name||'Message')+' copy';setEmbed(d)};$('emb_addfield').onclick=()=>{addEmbedField();renderEmbed()};
async function saveCurrentEmbed(){const r=await api('embed-save',readEmbed());embID=r.post.id;await loadEmbeds();setEmbed(r.post.draft,r.post.published);return r.post}
$('emb_save').onclick=()=>action($('emb_save'),async()=>{await saveCurrentEmbed();toast('Draft saved. Publish to apply it in Discord.')});
$('emb_publish').onclick=()=>action($('emb_publish'),async()=>{const p=await saveCurrentEmbed();toast(p.published?'Updating the posted message…':'Posting your embed…');const r=await api('embed-publish',{id:p.id});await loadEmbeds();setEmbed(r.post.draft,r.post.published);toast(r.warning||'Embed published. Its configured role action is ready.',!!r.warning)});
$('emb_rules').onclick=()=>{const d=blankEmbed();d.name='Workshop rules';d.title='Mubble’s Workshop — rules';d.mode='button';d.description=`Nothing complicated. Just a few things so this stays a place people actually want to hang out.

**1. Don’t be a dick.**
Banter is fine. Harassing someone, dogpiling them or carrying on after they’ve asked you to stop isn’t. You can disagree without making it personal.

**2. No slurs.**
Racism, homophobia, transphobia and similar shit aren’t welcome here. Posting slurs gets you banned, including in jokes or quotes.

**3. Swearing is fine.**
You don’t need to watch every word. Just don’t fill the chat with it or use it to constantly insult people. The bot removes messages that go over the swear limit.

**4. No spam or unwanted advertising.**
Don’t flood channels, repeatedly ping people or DM members to promote your stuff. Sharing something you made is welcome; posting the same link everywhere isn’t.

**5. Keep it SFW.**
No porn, gore or shock content. That includes profile pictures, usernames and links.

**6. Respect people’s privacy.**
Don’t post someone’s personal information, private messages or photos without their permission. Don’t pressure anyone to share theirs either.

**7. Give credit where it’s due.**
Share your builds, mods, art, videos or whatever you’re working on. Just don’t claim someone else’s work as yours. No scams or malicious downloads.

**8. Listen when a mod steps in.**
If you’re asked to stop or move a conversation, do that. If you think a decision was unfair, message a mod instead of turning the whole channel into an argument.`;setEmbed(d);toast('Rules template loaded. Choose a channel and your read-the-rules role, then publish.')};
loadEmbeds().then(()=>setEmbed(blankEmbed())).catch(e=>toast(e.message,true));
